services:
  - type: web
    name: lostandfound
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: lostandfound_db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: MAIL_SERVER
        value: "smtp.gmail.com"
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        value: "lostandfoundthingsportal@gmail.com"
      - key: MAIL_PASSWORD
        value: "qxdj vjcw pums fiyz"
      - key: MAIL_DEFAULT_SENDER
        value: "lostandfoundthingsportal@gmail.com"
      - key: RENDER
        value: "true"
    autoDeploy: true

databases:
  - name: lostandfound_db
    plan: free
    databaseName: lostandfound
    user: lostandfound_user